lets see if branch validation works

diff --git a/.github/workflows/infracost_deploy.yml b/.github/workflows/infracost_deploy.yml
--- a/.github/workflows/infracost_deploy.yml
+++ b/.github/workflows/infracost_deploy.yml
@@ -1,11 +1,26 @@
 name: Infracost Analysis of Ephemeral Envrioment
-on:
-  push:
-    branches:
-      - main
+on: push
 jobs:
+  verify-branch-name:
+    runs-on: ubuntu-latest
+    outputs:
+      is_valid: ${{ steps.check_branch_name.outputs.is_valid }}
+    steps:
+        - name: verify-branch-name
+          id: check_branch_name
+          run: |
+            if [[ "${{ github.ref_name }}" =~ ^[A-Z]{3,7}-[0-9]{1,5}$ ]]; then
+              echo "Branch name is valid."
+              echo "::set-output name=is_valid::true"
+            else
+              echo "Invalid branch name. The branch name correspond to a Jira issue key."
+              echo "::set-output name=is_valid::false"
+              exit 1
+            fi
   get-cost-analysis:
     runs-on: ubuntu-latest
+    needs: verify-branch-name
+    if: ${{ needs.verify-branch-name.outputs.is_valid == 'true' }}
     env:
         TF_DIR: ./IaC
         TF_ENV: dev   
